export const ADD_QUESTION = 'ADD_QUESTION'
export const ANSWER_QUESTION = 'ANSWER_QUESTION'

export const SET_AUTHED_USER = 'SET_AUTHED_USER'
export const REMOVE_AUTHED_USER = 'REMOVE_AUTHED_USER'

export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS'

export const RECEIVE_USERS = 'RECEIVE_USERS'
